### ISSUE TITLE
Wjet init - No such file or directory

### ISSUE THREAD

**Issue by romansopov** [webix-hub/wjet#2]
**root@portal:/home/app/1# npm install wjet -g**
/usr/bin/wjet -> /usr/lib/node_modules/wjet/wjet.js
wjet@0.1.0 /usr/lib/node_modules/wjet
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── lodash.template@3.6.2 (lodash._reinterpolate@3.0.0, lodash._basetostring@3.0.1, lodash._basevalues@3.0.0, lodash.escape@3.0.0, lodash.restparam@3.6.1, lodash._basecopy@3.0.1, lodash.templatesettings@3.1.0, lodash._isiterateecall@3.0.9, lodash.keys@3.1.2)
├── event-stream@3.3.2 (pause-stream@0.0.11, stream-combiner@0.0.4, duplexer@0.1.1, from@0.1.3, map-stream@0.1.0, split@0.3.3, through@2.3.8)
├── vinyl-fs@2.2.1 (is-valid-glob@0.3.0, object-assign@4.0.1, graceful-fs@4.1.2, strip-bom-stream@1.0.0, strip-bom@2.0.0, through2-filter@2.0.0, vinyl@1.0.0, gulp-sourcemaps@1.6.0, mkdirp@0.5.1, through2@2.0.0, merge-stream@1.0.0, duplexify@3.4.2, glob-stream@5.0.0)
├── inquirer@0.10.1 (strip-ansi@3.0.0, ansi-regex@2.0.0, ansi-escapes@1.1.0, figures@1.4.0, cli-width@1.1.0, rx-lite@3.1.2, through@2.3.8, chalk@1.1.1, cli-cursor@1.0.2, readline2@1.0.1, run-async@0.1.0, lodash@3.10.1)
└── bower@1.6.3

**root@portal:/home/app/1# wjet init**
: No such file or directory

**Comment by mkozhukh** [comment]
Fixed
